package com.app_tiny_tweet.activities;

import android.content.Intent;
import android.os.Bundle;
import android.text.TextUtils;
import android.view.View;
import android.widget.Button;
import android.widget.EditText;
import android.widget.Toast;

import androidx.appcompat.app.AppCompatActivity;

import com.app_tiny_tweet.R;
import com.app_tiny_tweet.model.Post;

public class CreatePostActivity extends AppCompatActivity {
    private EditText etPostContent;
    private Button btnSubmitPost;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_create_post);

        etPostContent = findViewById(R.id.etPostContent);
        btnSubmitPost = findViewById(R.id.btnSubmitPost);

        btnSubmitPost.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                String postContent = etPostContent.getText().toString().trim();

                if (TextUtils.isEmpty(postContent)) {
                    Toast.makeText(CreatePostActivity.this, "Post content cannot be empty", Toast.LENGTH_SHORT).show();
                } else {
                    // Simulate creating a post (In a real app, save the post to a database or server)
                    createPost(postContent);

                    // Redirect to AllPostsActivity
                    Intent intent = new Intent(CreatePostActivity.this, HomeActivity.class);
                    intent.putExtra("tab_index", 0); // Pass the tab index to open "Todos os posts"
                    startActivity(intent);
                    finish();
                }
            }
        });
    }

    private void createPost(String content) {
        // Here you would typically save the post to your database or server
        // For this example, we'll just create a Post object and show a toast
        String id = "1"; // This would be generated by your database
        String userId = "currentUserId"; // Replace with the actual user ID
        String creationDate = "2024-06-16"; // Use the current date in a real app

        Post newPost = new Post(id, content, creationDate, userId);
        Toast.makeText(this, "Post created: " + newPost.getContent(), Toast.LENGTH_SHORT).show();
    }
}